This script reads experimental results derived from EC072 progrenesis analysis.

In [ ]:
Data available is both normalized and raw. Visualize both and decide.

In [1]:
import pandas

# user-defined variables

In [3]:
experiment_one_input_file = '/home/adrian/projects/vigur/data/lipidomics/072/progenesis/HPMVEC_POSB1_1andB1_2.csv'
experiment_two_input_file = '/home/adrian/projects/vigur/data/lipidomics/072/progenesis/HPMVEC_POSB2_1andB2_2.csv'

# read information

In [4]:
df = pandas.read_csv(experiment_one_input_file)
df.shape

(494, 209)

# manipulate data

In [ ]:
## check that index is unique

In [10]:
print(df['Unnamed: 0'].shape)
print(len(list(set(df['Unnamed: 0']))))

(494,)

In [16]:
df.rename(columns={'Unnamed: 0': 'uniqueID'}, inplace=True)
df

,uniqueID,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 199,Unnamed: 200,Unnamed: 201,Unnamed: 202,Unnamed: 203,Unnamed: 204,Unnamed: 205,Unnamed: 206,Unnamed: 207,Unnamed: 208
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Compound,Neutral mass (Da),m/z,Charge,Retention time (min),Chromatographic peak width (min),Identifications,Anova (p),q Value,Max Fold Change,...,Accepted Compound ID,Accepted Description,Adducts,Formula,Score,Fragmentation Score,Mass Error (ppm),Isotope Similarity,Retention Time Error (mins),Compound Link
2,4.32_600.2622m/z,NaN,600.262199185733,1,4.31853333333333,0.0648500000000007,0,0,0,38373.8519466977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.17_319.1463m/z,NaN,319.146338165776,1,2.17235,0.205816666666667,0,0,0,6885.37637814429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2.29_300.9931m/z,NaN,300.993055791382,1,2.28628333333333,0.249516666666667,0,0,0,3725.86445734503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,4.35_571.3446m/z,NaN,571.344633754983,1,4.34556666666667,0.0977333333333332,0,0.999999933338617,0.999999999994059,5.82596175866323,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
490,5.43_452.3433m/z,NaN,452.343293857851,1,5.42981666666667,0.119366666666666,0,0.999999955383498,0.999999999994059,6.37798634969464,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
491,4.32_483.3659m/z,NaN,483.365851450019,1,4.32395,0.146366666666666,0,0.999999957212986,0.999999999994059,9.60395849231868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,8.19_563.4591m/z,NaN,563.459121111676,1,8.18795,0.162583333333332,0,0.999999970070085,0.999999999994059,3.44301086850698,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,5.95_530.4041n,530.40412949134,531.41140592334,1,5.95,0.249516666666667,0,0.99999999628984,0.999999999994059,13.194045239698,...,NaN,NaN,"M+H, M+Na",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
 We have raw and normalized abundances. Plot and decide